# Copyright (c) 2024 Rafael Guterres Jeffman
# See the file COPYING for license details.
---
name: Avaliação
run-name: 
on:
  - push
  - pull_request
jobs:
  run_tests:
    name: Executa os testes de avaliação
    runs-on: ubuntu-latest
    env:
      RUN_IN_UBUNTU: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Configura ambiente
        run: sudo apt-get install -y catch2 valgrind
      - name: Build
        shell: bash
        run: |
          mkdir .result
          make -k
      - name: Testes de comportamento
        if: ${{ always() }}
        run: |
          make test > >(tee result.raw) || err=1
          grep -v -e '^g\+\+' -e "=======" -e "^Randomness" -e "^All tests" -e "rm " -e "^ *$" < result.raw > .result/RESULT
          exit ${err:-0}
      - name: Testes de gerenciamento de memória
        if: ${{ always() }}
        shell: bash
        run: |
          make memtest > >(tee result.raw) || err=1
          grep -v -e '^g\+\+' -e "rm " -e "^ *$" < result.raw > .result/MEMTEST
          exit ${err:-0}
      - name: Arquiva resultados dos testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: homework_evaluation.${{ github.run_id }}
          path: .result
          retention-days: 90
  report_result:
    name: Resultados da avaliação
    if: ${{ always() }}
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: homework_evaluation.${{ github.run_id }}
      - name: Resultado
        shell: bash
        run: |
          sed "s/^-en* *//" < RESULT
          echo
          sed "s/^-en* *//" < MEMTEST
